### ISSUE TITLE
Not working on tables

### ISSUE THREAD

**Issue by mradzinski** [BeSite/jQuery.dotdotdot#81]
If you try applying dotdotdot to a td element the same remains unchanged without ellipsis at the end.

**Comment by Emnalyeriar** [comment]
I have a similar problem. I have a wrapper with display table and inside two divs with display table-cell so I can use vertical align middle. As you said text inside table-cell remains unchanged. Did you find a solution to this?

**Comment by FrDH** [comment]
I guess you could wrap all content in a `<span>`.

**Comment by mradzinski** [comment]
Not really. If I remember correctly I wrapped the cell content (which it was a simple <p> block) in a span block and it didn't work. Didn't find a solution so I actually had to move on and give up on this.

**Comment by FrDH** [comment]
While measuring the contents height, the plugin wraps the truncated element in a DIV. My guess is thats where it stops working, since wrapping a TD in a DIV probably isn't supported by any browser.
When you wrap the content in a DIV, and fire the plugin on that DIV (not the TD), there should be no problem because a DIV can be wrapped in a DIV.
