### ISSUE TITLE
&hellip; as ellipsis

### ISSUE THREAD

**Issue by thorsten** [BeSite/jQuery.dotdotdot#92]
As mentioned in #77, HTML is not allowed as ellipsis. Sadly, even &hellip; is not working, too. But that would be much better than adding three dots...

**Comment by HugoArts** [comment]
Using a Unicode ellipsis character works for me if I escape it:

```javascript
$('div.wrapper').dotdotdot({ ellipsis: '\u2026 ' });
```

However, in general I strongly believe that using &hellip; or an actual unicode ellipsis character should be the default. A proper ellipsis can't be replaced by 3 periods, the spacing is wrong.

**Comment by jpotterm** [comment]
:+1:

**Comment by jpotterm** [comment]
@FrDH Why did you close this? It doesn't look like this has been fixed in master. Is this something you disagree with? `&hellip;` should definitely be the default. There's no reason ever to use three periods as an ellipsis.

**Comment by FrDH** [comment]
According to HugoArts, you can use a unicode ellipsis if you escape it.

Since this plugin is considered to be donationware, but almost no-one ever makes a donation, I decided to no longer actively maintain the plugin. Therefor I'm not going to make any changes that possibly introduces new issues if there is an alternative.
If the plugin works for you, you can keep using it. Also feel free to make improvements and submit a pull request. If the plugin doesn't work for you, there's a few alternatives out there you could give a try.
